/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Prediction = IDL.Record({
  'suggestion' : IDL.Text,
  'confidence' : IDL.Nat,
});
export const Time = IDL.Int;
export const PeriodResult = IDL.Record({
  'number' : IDL.Nat,
  'timestamp' : Time,
  'periodId' : IDL.Text,
});

export const idlService = IDL.Service({
  'getNextPrediction' : IDL.Func([], [Prediction], ['query']),
  'getRecentResults' : IDL.Func([IDL.Nat], [IDL.Vec(PeriodResult)], ['query']),
  'submitPeriodResult' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Prediction = IDL.Record({
    'suggestion' : IDL.Text,
    'confidence' : IDL.Nat,
  });
  const Time = IDL.Int;
  const PeriodResult = IDL.Record({
    'number' : IDL.Nat,
    'timestamp' : Time,
    'periodId' : IDL.Text,
  });
  
  return IDL.Service({
    'getNextPrediction' : IDL.Func([], [Prediction], ['query']),
    'getRecentResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PeriodResult)],
        ['query'],
      ),
    'submitPeriodResult' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };